db_dir: "databases" # relative to workflow base or absolute
search:
  # NOTE: make sure to adjust/remove --taxonlist in args for custom databases
  db: "rvdb80.dmnd"
  evalue: 1e-4
  min_length_aa: 83
  taxonlist: "--taxonlist 2732396,2731342"
  # expert
  other_args: "-c1 -b6 -F15 --range-culling -k 20 --outfmt 6"
  chop_window: 60000
  chop_step: 50000

retrosearch:
  db: "uniref50.dmnd"
  evalue: 1e-4
  # expert
  other_args: "-c1 -b6 -F15 --range-culling -k 20 --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore stitle staxids sscinames sskingdoms skingdoms sphylums"
 
